spring.application.name=todo

# Database (Railway environment variables)
spring.datasource.url=${jdbc:mysql://centerbeam.proxy.rlwy.net:50307/railway}
spring.datasource.username=${railway}
spring.datasource.password=${XJlzjlEolYbWlcRjrbUTtvExebnAfPhR}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Server Port (Railway requirement)
server.port=${PORT:8080}